name: 'Setup ASIO SDK'
description: 'Downloads and sets up the Steinberg ASIO SDK'
runs:
  using: "composite"
  steps:
    - name: Download ASIO SDK
      shell: bash
      run: |
        if [ ! -d "asio" ]; then
          mkdir -p asio
          curl -L https://download.steinberg.net/sdk_downloads/asiosdk2.3.1.zip -o asiosdk.zip
          unzip asiosdk.zip -d asio
          # Move contents up if it created a subfolder
          if [ -d "asio/ASIOSDK2.3.1" ]; then
            mv asio/ASIOSDK2.3.1/* asio/
          fi
        fi
        echo "CPAL_ASIO_DIR=$(pwd)/asio" >> $GITHUB_ENV
