name: 'Determine MSRV'
description: 'Determines the minimum Rust version required for the current platform and features'
inputs:
  platform-msrv:
    description: 'Minimum Rust version for the platform'
    required: true
  jack-msrv:
    description: 'Minimum Rust version for the jack feature'
    required: true
outputs:
  all-features:
    description: 'Minimum Rust version for all features'
    value: ${{ steps.msrv.outputs.all-features }}
runs:
  using: "composite"
  steps:
    - name: Determine MSRV
      id: msrv
      shell: bash
      run: |
        PLATFORM_MSRV=${{ inputs.platform-msrv }}
        JACK_MSRV=${{ inputs.jack-msrv }}
        
        # Simple max version logic
        if [[ "$JACK_MSRV" > "$PLATFORM_MSRV" ]]; then
          echo "all-features=$JACK_MSRV" >> $GITHUB_OUTPUT
        else
          echo "all-features=$PLATFORM_MSRV" >> $GITHUB_OUTPUT
        fi
